logging:
  level:
    ROOT: INFO
    org.dotwebstack: DEBUG

  template:
    baseUrl: ${BASE_URL:https://ruimte.omgevingswet.overheid.nl/ruimtelijke-plannen/api/opvragen/v4}

  openapi:
    xdwsStringTypes:
      - geometry
server:
  port: 8081
